### ISSUE TITLE
Unused argument in calling download_daymet

### ISSUE THREAD

**Issue by gponce-ars** [khufkens/phenor#17]
In the following lines in `format_phenocam.r` there's a call to `daymetr::download_daymet` where there's an unused argument. When format_phenocam is called you get this error:

`Error in daymetr::download_daymet(start = end, end = end, internal = TRUE,  : 
  unused argument (quiet = TRUE)`

https://github.com/khufkens/phenor/blob/dcad39cc13c8a9fd7d6f11f025507c2c6577ce06/R/format_phenocam.r#L83

https://github.com/khufkens/phenor/blob/dcad39cc13c8a9fd7d6f11f025507c2c6577ce06/R/format_phenocam.r#L225

Same case for these:
phenor/R/format_npn.r
phenor/R/format_modis.r
phenor/R/format_gee.r

I can see the difference in your package phenocamr, where download_daymet function call already has the right parameter "silent=TRUE" instead of "quiet=TRUE".
As in:
phenocamr/R/merge_daymet.r

**Comment by khufkens** [comment]
Thanks for catching this. I've rewritten some of the daymet routines but it seems that things didn't propagate to the phenor package.

Fixed as per:
https://github.com/khufkens/phenor/commit/605e09b4dfeca743b205257f4411eac72b23fdd6

**Comment by gponce-ars** [comment]
format_phenocam.r  still has the "silent = TRUE", right?
I didn't have a chance to test it before and today I just re-installed "phenor" and still get that error of "unused argument (quiet=TRUE)"
